version: 2.0

pipelines:
  - name: Execute MAIN and Python Script
    trigger_mode: ON_EVERY_PUSH  # Trigger pipeline on every code push
    ref_name: main  # Branch to monitor (e.g., "main" branch)
    actions:
      - action: Make MAIN Executable
        type: BUILD
        docker_image_name: ubuntu
        docker_image_tag: "latest"
        working_directory: /app  # Files will be in /app directory
        script:
          - echo "Making MAIN executable..."
          - chmod +x MAIN  # Grant execute permission to MAIN
          - echo "Executing MAIN..."
          - ./MAIN  # Run MAIN script

      - action: Run Python Script
        type: BUILD
        docker_image_name: python
        docker_image_tag: "3.10"
        working_directory: /app
        script:
          - echo "Checking dependencies..."
          - pip install -r requirements.txt || echo "No dependencies to install"
          - echo "Running Python script..."
          - python MAIN.py  # Run Python script