version: 2.0

pipelines:
  - name: Install Dependencies and Run Script
    trigger_mode: ON_EVERY_PUSH
    steps:
      - action: Install dependencies
        script:
          # Use virtual environment to avoid permission issues
          - python3 -m venv venv
          - source venv/bin/activate
          - pip install -r requirements.txt
          # Output installed packages for verification
          - pip list
      - action: Run MAIN Script
        script:
          # Ensure MAIN file is executable
          - chmod +x MAIN
          # Run the MAIN script
          - ./MAIN
          # OR use Python to run the script
          # python3 MAIN.py
      - action: Clean up
        script:
          # Deactivate virtual environment
          - deactivate
